import { contractDetailMobileStyles } from '@/components/business/contract-detail-mobile-styles'
import { contractListMobileStyles } from '@/components/business/contract-list-mobile-styles'

export const addRoomMobileStyles = {
  pageSection: contractListMobileStyles.pageSection,
  card: 'rounded-lg border border-gray-100 shadow-sm gap-3 py-3 sm:gap-6 sm:py-6',
  cardHeader: 'gap-1 px-3 pb-0 sm:gap-1.5 sm:px-6',
  cardTitleRow: 'flex items-center justify-between gap-2',
  cardTitle: 'text-base sm:text-lg',
  cardActionButton: 'h-8 px-3 text-sm sm:h-9',
  cardDescription: 'text-sm leading-5 text-gray-500',
  cardContent: 'space-y-3 px-3 pt-0 pb-3 sm:space-y-4 sm:px-6 sm:pb-6',
  formPanel: 'space-y-3 rounded-lg border border-gray-100 bg-gray-50/80 p-3 sm:p-4',
  formPanelAccent: 'border-blue-200 bg-blue-50',
  formPanelHeader: 'flex items-center justify-between gap-2',
  formPanelTitle: 'text-sm font-medium leading-5 text-blue-900',
  fieldStack: 'space-y-1.5',
  input: 'h-10 text-sm placeholder:text-sm sm:h-11 sm:text-base sm:placeholder:text-base',
  select:
    'h-10 w-full rounded-md border border-gray-200 bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-blue-500 sm:h-11 sm:text-base',
  actionRow: 'flex flex-wrap gap-2',
  buildingList: 'grid grid-cols-1 gap-2.5',
  buildingItem:
    'rounded-lg border border-gray-100 p-3 transition-colors hover:bg-gray-50 sm:p-3.5',
  buildingItemSelected: 'border-blue-200 bg-blue-50 hover:bg-blue-50',
  buildingRow: 'flex items-start gap-2.5',
  buildingIcon: 'mt-0.5 h-4 w-4 shrink-0 text-gray-400 sm:h-5 sm:w-5',
  buildingContent: 'min-w-0 flex-1 cursor-pointer',
  buildingName: 'text-sm font-medium leading-5 text-gray-900',
  buildingAddress: 'mt-0.5 text-sm leading-5 text-gray-500',
  buildingMeta: 'text-[11px] leading-4 text-gray-400',
  iconActionButton: 'h-8 w-8 p-0',
  numberGroup: 'flex items-center gap-2',
  numberInput: 'h-10 flex-1 text-sm sm:h-11 sm:text-base',
  stepperWrap: 'flex flex-col',
  stepperButton:
    'h-6 min-w-8 rounded-t border border-gray-300 bg-gray-100 px-2 text-[10px] leading-none hover:bg-gray-200',
  stepperButtonBottom:
    'h-6 min-w-8 rounded-b border border-t-0 border-gray-300 bg-gray-100 px-2 text-[10px] leading-none hover:bg-gray-200',
  twoColGrid: 'grid grid-cols-2 gap-3 sm:gap-4',
  infoBox: contractDetailMobileStyles.infoBox,
  infoText: contractDetailMobileStyles.infoText,
  primaryButton: 'h-10 w-full text-sm sm:h-11 sm:text-base',
  errorText: 'text-center text-xs text-red-500',
  previewHeaderRow: 'flex items-start justify-between gap-2',
  previewHeaderActions: 'shrink-0',
  previewButton: 'h-8 min-w-[96px] text-sm sm:h-9 sm:min-w-[108px]',
  previewFloorSection: 'space-y-2',
  previewFloorHeader: 'flex items-center gap-2',
  previewFloorTitle: 'text-sm font-medium leading-5 text-gray-900',
  previewFloorBadge: 'px-2 py-0.5 text-[11px]',
  previewGrid: 'grid grid-cols-2 gap-2.5 sm:grid-cols-3 md:grid-cols-4 sm:gap-3',
  previewItem:
    'rounded-lg border border-gray-100 bg-gray-50/90 p-2.5 sm:p-3',
  previewItemHeader: 'mb-1.5 flex items-start justify-between gap-2',
  previewItemTitle: 'text-sm font-medium leading-5 text-gray-900',
  previewItemBadge: 'shrink-0 text-[11px]',
  previewItemMeta: 'space-y-1 text-[11px] leading-4 text-gray-600',
  previewEmpty: 'py-10 text-center',
  previewEmptyText: 'text-sm leading-5 text-gray-500',
  previewEmptySubtle: 'mt-1 text-sm leading-5 text-gray-500',
} as const
