import { billDetailMobileStyles } from '@/components/business/bill-detail-mobile-styles'
import { contractDetailMobileStyles } from '@/components/business/contract-detail-mobile-styles'
import { meterReadingEntryMobileStyles } from '@/components/business/meter-reading-entry-mobile-styles'

export const batchMeterReadingMobileStyles = {
  pageSection: billDetailMobileStyles.pageSection,
  card: billDetailMobileStyles.card,
  cardHeader: billDetailMobileStyles.cardHeader,
  cardHeaderRow: billDetailMobileStyles.cardHeaderRow,
  cardTitle: billDetailMobileStyles.cardTitle,
  cardContent: billDetailMobileStyles.cardContent,
  noteCard: 'rounded-lg border border-orange-200 bg-orange-50 shadow-sm gap-0 py-0',
  noteContent: 'space-y-3 p-3 sm:p-4',
  noteRow: 'flex items-start gap-3',
  noteTitle: 'text-sm font-medium leading-5 text-gray-900',
  noteList: 'mt-1.5 space-y-1 text-xs leading-5 text-gray-600',
  strategyCard: billDetailMobileStyles.card,
  strategyHeader: billDetailMobileStyles.cardHeader,
  strategyContent: 'space-y-3 px-3 pt-0 pb-3 sm:space-y-4 sm:px-6 sm:pb-6',
  strategyRow: 'flex items-start justify-between gap-3',
  strategyMeta: 'space-y-0.5',
  strategyLabel: 'text-sm font-medium leading-5 text-gray-900',
  strategyHint: 'text-xs leading-5 text-gray-500',
  strategyActions: 'flex flex-wrap items-center gap-2',
  strategyButton: 'h-8 px-3 text-xs sm:text-sm',
  strategyFootnote: 'text-xs leading-5 text-gray-500',
  strategyInfoBox: 'rounded-lg border border-blue-200 bg-blue-50 p-2.5 sm:p-3',
  strategyInfoText: 'text-sm leading-5 text-blue-700',
  readingCard: meterReadingEntryMobileStyles.meterCard,
  readingHeader: 'gap-1 px-3 pb-0 pt-3 sm:gap-1.5 sm:px-6 sm:pt-5',
  readingTitleRow: 'flex items-center justify-between gap-2',
  readingCountText: 'text-sm leading-5 text-gray-500',
  readingContent: 'p-0',
  mobileList: 'block md:hidden',
  mobileItem: 'space-y-2.5 border-b px-3 py-3 sm:px-4 sm:py-4',
  mobileItemHeader: 'flex items-start justify-between gap-2',
  mobileRoomTitle: 'text-sm font-medium leading-5 text-gray-900',
  mobileMetaRow: 'mt-1 flex flex-wrap items-center gap-2',
  meterInfoGroup: meterReadingEntryMobileStyles.meterInfoGroup,
  meterIdentity: meterReadingEntryMobileStyles.meterIdentity,
  meterMetaRow: meterReadingEntryMobileStyles.meterMetaRow,
  mobileMeterName: 'text-sm leading-5 text-gray-600',
  mobileContractMeta: 'text-xs leading-4 text-gray-500',
  mobileFieldsGrid: 'grid grid-cols-2 gap-3',
  mobileFieldLabel: 'text-[11px] leading-4 text-gray-500',
  mobileFieldValue: 'font-mono text-sm font-medium leading-5 text-gray-900',
  mobileInput: meterReadingEntryMobileStyles.input,
  mobileResultGrid: 'grid grid-cols-2 gap-3 border-t border-gray-100 pt-2.5',
  resultValueUsage: 'font-mono text-sm font-medium leading-5 text-blue-600',
  resultValueAmount: 'font-mono text-sm font-medium leading-5 text-green-600',
  fieldError: 'mt-1 text-xs leading-4 text-red-600',
  fieldWarning: 'mt-1 text-xs leading-4 text-orange-600',
  desktopTableWrap: 'hidden overflow-x-auto md:block',
  desktopTableHead: 'border-b bg-gray-50',
  desktopTableHeadCell: 'p-3 text-left text-sm font-medium text-gray-700',
  desktopTableHeadCellCenter: 'p-3 text-center text-sm font-medium text-gray-700',
  desktopTableHeadCellRight: 'p-3 text-right text-sm font-medium text-gray-700',
  desktopRow: 'border-b hover:bg-gray-50',
  desktopCell: 'p-3 align-top',
  desktopCellCenter: 'p-3 text-center align-top',
  desktopCellRight: 'p-3 text-right align-top',
  desktopRoomCell: 'flex items-center gap-2',
  desktopRoomBadge:
    'flex h-8 w-8 items-center justify-center rounded bg-blue-100 text-xs font-medium text-blue-600',
  desktopRoomNumber: 'text-sm font-medium leading-5 text-gray-900',
  desktopRoomMeta: 'text-xs leading-4 text-gray-500',
  desktopMeterWrap: 'flex items-center gap-2',
  desktopMeterName: 'text-sm leading-5 text-gray-700',
  desktopInputWrap: 'flex items-center justify-center',
  desktopInput:
    'w-24 rounded-md border px-2.5 py-1.5 text-center font-mono text-sm outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
  desktopMuted: 'text-sm leading-5 text-gray-400',
  summaryCard: billDetailMobileStyles.summaryCard,
  summaryMetaRow: 'grid grid-cols-2 gap-2.5 sm:grid-cols-5 sm:gap-4',
  summaryMetaBlock: 'rounded-lg bg-white/70 px-3 py-2.5 text-center',
  summaryMetaLabel: 'text-[11px] font-medium leading-4 text-gray-500',
  summaryMetaValue: 'mt-1 text-lg font-semibold leading-5 text-gray-900 sm:text-xl',
  actionRow: billDetailMobileStyles.actionsRow,
  actionButton: billDetailMobileStyles.actionButton,
  secondaryActionButton: 'h-9 w-full text-sm sm:w-auto sm:flex-none',
} as const
