import { contractDetailMobileStyles } from '@/components/business/contract-detail-mobile-styles'
import { contractListMobileStyles } from '@/components/business/contract-list-mobile-styles'

export const meterReadingHistoryMobileStyles = {
  pageSection: contractListMobileStyles.pageSection,
  actionsGrid: contractDetailMobileStyles.actionsGrid,
  actionButton: contractDetailMobileStyles.actionButton,
  toolbarCard: contractListMobileStyles.toolbarCard,
  toolbarStack: contractListMobileStyles.toolbarStack,
  toolbarRow: contractListMobileStyles.toolbarRow,
  searchWrap: contractListMobileStyles.searchWrap,
  searchIcon: contractListMobileStyles.searchIcon,
  searchInput: contractListMobileStyles.searchInput,
  filtersRow: 'flex flex-wrap gap-2',
  selectTrigger:
    'h-10 w-[calc(50%-0.25rem)] min-w-[140px] text-sm sm:h-11 sm:w-40 sm:text-base',
  resultText: contractListMobileStyles.resultText,
  statsGrid: contractListMobileStyles.statsGrid,
  statsCard: contractListMobileStyles.statsCard,
  statsContent: contractListMobileStyles.statsContent,
  statsInner: contractListMobileStyles.statsInner,
  statsLabel: contractListMobileStyles.statsLabel,
  statsValue: contractListMobileStyles.statsValue,
  statusPanel: 'rounded-lg border border-gray-100 bg-white p-3 shadow-sm sm:p-4',
  statusPanelHeader: 'flex flex-wrap items-start justify-between gap-2',
  statusPanelTitle: 'text-sm font-medium leading-5 text-gray-900',
  statusPanelText: 'text-sm leading-5 text-gray-600',
  statusPanelList: 'mt-2 space-y-1 text-sm leading-5 text-gray-600',
  statusPanelSection: 'mt-3 border-t border-gray-100 pt-3',
  issueList: 'mt-2 space-y-2.5',
  issueCard: 'rounded-lg border border-yellow-200 bg-yellow-50 p-2.5',
  issueTitleRow: 'flex items-center justify-between gap-2',
  issueTitle: 'text-sm font-medium leading-5 text-gray-900',
  issueMeta: 'text-[11px] leading-4 text-gray-500',
  issueText: 'mt-1 text-sm leading-5 text-gray-600',
  listStack: 'space-y-2.5',
  emptyState: contractListMobileStyles.emptyState,
  emptyTitle: contractListMobileStyles.emptyTitle,
  emptyText: contractListMobileStyles.emptyText,
  card: contractListMobileStyles.card,
  cardContent: contractListMobileStyles.cardContent,
  cardHeader: contractListMobileStyles.cardHeader,
  cardLeading: contractListMobileStyles.cardLeading,
  cardTitleRow: 'flex items-center gap-2',
  cardTitle: contractListMobileStyles.cardTitle,
  cardMeta: contractListMobileStyles.cardMeta,
  badgeRow: 'flex flex-wrap items-center gap-1.5',
  summaryGrid:
    'grid grid-cols-2 gap-2 rounded-lg bg-gray-50 p-2.5 text-sm sm:grid-cols-4 sm:gap-3',
  summaryItem: 'space-y-0.5',
  summaryLabel: contractListMobileStyles.detailLabel,
  summaryValue: contractListMobileStyles.detailValue,
  summaryValueUsage: 'text-sm font-medium leading-5 text-blue-600',
  summaryValueAmount: 'text-sm font-medium leading-5 text-green-600',
  footerRow: 'mt-1.5 flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px] leading-4 text-gray-500',
  remarkBox: 'mt-2 rounded-lg border border-amber-100 bg-amber-50 p-2.5',
  remarkText: 'text-sm leading-5 text-gray-700',
  cardActions: 'ml-2 shrink-0',
  cardActionButton: 'h-8 w-8 p-0',
} as const
