export const billListMobileStyles = {
  pageSection: 'space-y-2.5 pb-2.5 sm:space-y-6 sm:pb-6',
  toolbarCard: 'rounded-lg border border-gray-100 bg-white p-2.5 shadow-sm sm:p-4',
  toolbarRow: 'flex items-stretch gap-2.5 sm:gap-3',
  toolbarActionButton: 'h-10 px-2.5 text-sm sm:h-9 sm:w-auto sm:px-4',
  searchIcon:
    'absolute top-1/2 left-2.5 h-4 w-4 -translate-y-1/2 transform text-gray-400 sm:left-3',
  searchInput:
    'h-10 w-full pr-3 pl-9 text-sm placeholder:text-sm sm:h-11 sm:pr-4 sm:pl-10 sm:text-base sm:placeholder:text-base',
  statsCard: 'gap-3 py-3 sm:gap-6 sm:py-6',
  statsHeader: 'gap-1 px-3 pb-0 sm:gap-1.5 sm:px-6',
  statsTitle: 'text-base sm:text-lg',
  statsContent: 'px-3 pt-0 pb-3 sm:px-6 sm:pb-6',
  statsGrid: 'grid grid-cols-2 gap-2.5 md:grid-cols-4 md:gap-4',
  statsItem: 'rounded-lg p-3 sm:p-4',
  statsValue: 'text-xl font-bold sm:text-2xl',
  statsLabel: 'mt-0.5 text-xs text-gray-600 sm:mt-1 sm:text-sm',
  statsDescription: 'mt-0.5 text-[11px] text-gray-500 sm:mt-1 sm:text-xs',
  filterCard: 'rounded-lg border border-gray-100 bg-white p-3 shadow-sm sm:p-4',
  filterTitle: 'mb-2.5 text-sm font-medium text-gray-900 sm:mb-3',
  filterActions: 'flex flex-wrap gap-1.5 sm:gap-2',
  filterButton:
    'flex min-h-8 items-center gap-1.5 px-2.5 py-1.5 text-sm sm:gap-2 sm:px-3',
  filterCountBadge: 'text-xs',
  mobileList: 'block space-y-2.5 lg:hidden',
  mobileSkeletonList: 'space-y-2.5 sm:space-y-3',
  compactCardContent: 'p-2.5 sm:p-3',
  compactCardHeader: 'mb-1.5 flex items-start justify-between gap-2',
  compactCardLeading: 'flex min-w-0 flex-1 items-start gap-1.5 sm:gap-2',
  compactIconBox:
    'flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-md sm:h-7 sm:w-7',
  compactTitle: 'truncate text-sm font-semibold leading-5 text-gray-900',
  compactMeta: 'text-muted-foreground truncate text-[11px] leading-4',
  compactBadge: 'ml-2 flex-shrink-0 px-2 py-0.5 text-[11px]',
  compactDetails: 'space-y-1',
  compactLabel: 'text-muted-foreground text-[11px] leading-4',
  compactValue: 'text-sm font-medium leading-5',
  compactDetailRow: 'flex items-center justify-between',
  compactDetailPairRow: 'flex items-start justify-between gap-3',
  compactDetailPairLabel: 'text-muted-foreground pt-0.5 text-[11px] leading-4',
  compactDetailPairValue:
    'max-w-[62%] text-right text-xs leading-4 text-gray-700',
  compactFooter: 'mt-1.5 border-t border-gray-100 pt-1.5 sm:mt-2 sm:pt-2',
  compactFooterRow: 'flex items-center justify-between',
  compactFooterLeading: 'flex min-w-0 items-center gap-1.5',
  compactFooterDot: 'h-1.5 w-1.5 rounded-full',
  compactOverdueInfo: 'shrink-0 text-[11px] font-medium leading-4 text-red-600',
} as const
