export const contractListMobileStyles = {
  pageSection: 'space-y-2.5 pb-2.5 sm:space-y-6 sm:pb-6',
  toolbarCard: 'rounded-lg border border-gray-100 bg-white p-2.5 shadow-sm sm:p-4',
  toolbarStack: 'space-y-2.5 sm:space-y-3',
  toolbarRow: 'flex flex-col gap-2.5 sm:flex-row sm:items-stretch sm:gap-3',
  searchWrap: 'relative flex-1',
  searchIcon:
    'absolute top-1/2 left-2.5 h-4 w-4 -translate-y-1/2 transform text-gray-400 sm:left-3',
  searchInput:
    'h-10 w-full pr-3 pl-9 text-sm placeholder:text-sm sm:h-11 sm:pr-4 sm:pl-10 sm:text-base sm:placeholder:text-base',
  selectWrap:
    'flex items-center gap-2 rounded-lg border border-gray-100 bg-gray-50/80 px-2.5 sm:w-48 sm:border-0 sm:bg-transparent sm:px-0',
  selectIcon: 'h-4 w-4 shrink-0 text-gray-400',
  select:
    'h-10 w-full rounded-md border border-gray-200 bg-white px-3 text-sm sm:h-11 sm:text-base',
  filterCard: 'rounded-lg border border-gray-100 bg-white p-3 shadow-sm sm:p-4',
  filterSection: 'space-y-2',
  filterHeader: 'text-sm font-medium text-gray-900',
  filterActions: 'flex flex-wrap gap-1.5 sm:gap-2',
  filterButton:
    'flex min-h-8 items-center gap-1.5 rounded-md px-2.5 py-1.5 text-sm sm:gap-2 sm:px-3',
  filterCount: 'text-xs',
  filterAlertButton:
    'border-orange-200 bg-orange-50 text-orange-700 hover:bg-orange-100 hover:text-orange-800',
  filterAlertButtonActive:
    'bg-orange-600 text-white hover:bg-orange-700 border-orange-600',
  filterAlertCount: 'bg-orange-100 text-orange-700',
  statsGrid: 'grid grid-cols-2 gap-2.5 md:grid-cols-4 md:gap-4',
  statsCard: 'gap-0 overflow-hidden rounded-lg border border-gray-100 py-0 shadow-sm',
  statsContent: 'p-3 sm:p-4',
  statsInner: 'flex items-center justify-between gap-3',
  statsLabel: 'text-xs text-gray-600 sm:text-sm',
  statsValue: 'mt-0.5 text-xl font-bold leading-6 text-gray-900 sm:mt-1 sm:text-2xl',
  statsIconBox: 'flex h-8 w-8 shrink-0 items-center justify-center rounded-full sm:h-10 sm:w-10',
  resultText: 'text-sm leading-5 text-gray-600',
  listGrid: 'grid grid-cols-1 gap-2.5 md:grid-cols-2 xl:grid-cols-3 xl:gap-4',
  emptyState: 'rounded-lg border border-gray-100 bg-white py-10 text-center shadow-sm',
  emptyTitle: 'mb-1 text-base font-medium text-gray-900',
  emptyText: 'text-sm text-gray-500',
  card: 'gap-0 overflow-hidden rounded-lg border border-gray-100 py-0 transition-all hover:shadow-md',
  cardContent: 'p-2.5 sm:p-3',
  cardHeader: 'mb-1.5 flex items-start justify-between gap-2',
  cardLeading: 'min-w-0 flex-1',
  cardTitle: 'truncate text-sm font-semibold leading-5 text-gray-900',
  cardMeta: 'truncate text-[11px] leading-4 text-gray-500',
  cardStatusCluster: 'ml-2 flex shrink-0 items-center gap-1.5 self-start',
  cardBadge: 'shrink-0 px-2 py-0.5 text-[11px]',
  detailStack: 'space-y-1',
  detailRow: 'flex items-center justify-between gap-3',
  detailPairRow: 'flex items-start justify-between gap-3',
  detailLabel: 'text-[11px] leading-4 text-gray-500',
  detailValue: 'text-sm font-medium leading-5 text-gray-900',
  detailPairValue: 'max-w-[62%] text-right text-xs leading-4 text-gray-700',
  footer: 'mt-1.5 border-t border-gray-100 pt-1.5 sm:mt-2 sm:pt-2',
  footerRow: 'flex items-center justify-between gap-3',
  footerMetaText: 'truncate text-xs font-medium leading-4 text-gray-700',
  footerMetaSubtle: 'shrink-0 text-[11px] leading-4 text-gray-500',
  footerHint: 'text-[11px] font-medium leading-4',
} as const
