import { contractDetailMobileStyles } from '@/components/business/contract-detail-mobile-styles'
import { contractListMobileStyles } from '@/components/business/contract-list-mobile-styles'
import { renterDetailMobileStyles } from '@/components/business/renter-detail-mobile-styles'
import { renterFormMobileStyles } from '@/components/business/renter-form-mobile-styles'

export const contractCreateMobileStyles = {
  pageSection: contractListMobileStyles.pageSection,
  form: 'space-y-2.5 pb-2.5 sm:space-y-6 sm:pb-6',
  noticeCard: 'rounded-lg border border-gray-100 bg-white p-2.5 shadow-sm sm:p-3',
  noticeMuted: 'border-gray-200 bg-gray-50 text-gray-600',
  noticeInfo: 'border-blue-200 bg-blue-50 text-blue-800',
  noticeRow: 'flex items-center gap-2',
  noticeSpinner:
    'h-4 w-4 animate-spin rounded-full border-b-2 border-current',
  noticeText: 'text-sm leading-5',
  card: renterDetailMobileStyles.card,
  cardHeader: renterDetailMobileStyles.cardHeader,
  cardTitle: renterDetailMobileStyles.cardTitle,
  cardDescription: 'text-sm leading-5 text-gray-500',
  cardContent: 'space-y-3 px-3 pt-0 pb-3 sm:space-y-4 sm:px-6 sm:pb-6',
  selectorStack: 'space-y-2.5',
  searchWrap: contractListMobileStyles.searchWrap,
  searchIcon: contractListMobileStyles.searchIcon,
  searchInput: contractListMobileStyles.searchInput,
  selectedCard: 'rounded-lg border border-blue-200 bg-blue-50 shadow-sm',
  selectedCardContent: 'p-2 sm:p-2.5',
  selectedRow: 'flex items-start justify-between gap-1.5',
  selectedLeading: 'flex min-w-0 flex-1 items-start gap-2',
  avatarBox:
    'flex size-8 shrink-0 items-center justify-center rounded-full bg-gray-100',
  avatarBoxSelected: 'bg-blue-100',
  avatarIcon: 'h-4 w-4 text-gray-600',
  avatarIconSelected: 'text-blue-600',
  selectedTitle: contractListMobileStyles.cardTitle,
  selectedMeta: 'mt-0.5 text-sm leading-4 text-gray-600',
  selectedSubtle: 'mt-0 text-[11px] leading-4 text-gray-500',
  selectedWarning: 'mt-0.5 text-xs leading-4 text-orange-600',
  selectedCheck: 'mt-0.5 h-4 w-4 shrink-0 text-blue-600',
  listWrap: 'max-h-64 space-y-2 overflow-y-auto pr-0.5',
  listGroup: 'space-y-2',
  listGroupTitle: 'px-0.5 text-sm font-medium leading-5 text-gray-700',
  optionCard: contractListMobileStyles.card,
  optionCardSelected: 'border-blue-200 bg-blue-50',
  optionCardContent: contractListMobileStyles.cardContent,
  optionRow: 'flex items-start justify-between gap-2',
  optionLeading: 'flex min-w-0 flex-1 items-start gap-2.5',
  optionTitle: contractListMobileStyles.cardTitle,
  optionMeta: 'mt-0.5 text-sm leading-5 text-gray-600',
  optionSubtle: 'mt-0.5 text-[11px] leading-4 text-gray-500',
  optionBadgeRow: 'mt-1 flex items-center gap-2',
  optionStatusText: 'text-xs leading-4 text-orange-600',
  optionFloorText: 'text-[11px] leading-4 text-gray-500',
  optionDisabledText: 'ml-1.5 text-xs leading-4 text-gray-500',
  optionCheck: 'mt-0.5 h-5 w-5 shrink-0 text-blue-600',
  emptyState: 'py-8 text-center text-sm text-gray-500',
  resultText: 'text-center text-xs leading-4 text-gray-500',
  fieldGrid: 'grid grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-4',
  fieldStack: 'space-y-1.5',
  label: 'text-sm font-medium text-gray-700',
  input: renterFormMobileStyles.input,
  select: renterFormMobileStyles.select,
  textarea: renterFormMobileStyles.textarea,
  helperText: 'text-xs leading-4 text-gray-500',
  inlineWarning: 'rounded-lg border border-amber-200 bg-amber-50 p-2.5 text-sm leading-5 text-amber-700',
  quickActions: 'flex flex-wrap gap-2',
  quickButton: 'h-8 px-3 text-sm sm:h-9',
  meterCard: 'rounded-lg border border-gray-100 bg-gray-50/80 p-3 sm:p-3.5',
  meterList: 'space-y-2.5',
  meterHeader: 'flex items-start justify-between gap-3',
  meterTitle: 'text-sm font-medium leading-5 text-gray-900',
  meterMeta: 'mt-0.5 text-xs leading-4 text-gray-500',
  meterPrice: 'text-right text-sm font-medium leading-5 text-gray-700',
  meterType: 'mt-0.5 text-[11px] leading-4 text-gray-500',
  meterInputRow: 'mt-2.5 flex flex-col gap-2.5 sm:flex-row sm:items-center',
  meterInput: 'h-10 w-full text-sm sm:w-32',
  meterUnit: 'text-sm leading-5 text-gray-500',
  infoBox: contractDetailMobileStyles.infoBox,
  infoText: contractDetailMobileStyles.infoText,
  actionsRow: 'grid grid-cols-2 gap-2.5 sm:max-w-sm',
  actionButton: 'h-10 w-full text-sm sm:h-10',
} as const
