export const meterReadingEntryMobileStyles = {
  meterCard: 'gap-0 overflow-hidden rounded-lg border py-0 shadow-sm',
  meterCardContent: 'p-2.5 sm:p-3',
  meterCardHeader: 'mb-1.5 flex items-center justify-between gap-2',
  meterInfoGroup: 'flex min-w-0 items-center gap-2',
  meterIdentity: 'min-w-0',
  meterTitleRow: 'flex items-center gap-2',
  meterName: 'text-sm font-medium leading-5 text-gray-900',
  meterMetaRow: 'mt-0.5 flex flex-wrap items-center gap-2',
  meterMeta: 'text-[11px] leading-4 text-gray-500',
  fieldsGrid: 'grid grid-cols-2 gap-3 md:grid-cols-4',
  fieldLabel: 'text-[11px] leading-4 text-gray-500',
  fieldValue: 'font-mono text-sm font-medium leading-5 text-gray-900',
  input:
    'w-full rounded-md border px-2.5 py-1.5 text-center font-mono text-sm outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
  resultValueUsage: 'font-mono text-sm font-medium leading-5 text-blue-600',
  resultValueAmount: 'font-mono text-sm font-medium leading-5 text-green-600',
  errorRow: 'mt-2 flex items-center gap-2 text-sm text-red-600',
  warningRow: 'mt-2 flex items-center gap-2 text-sm text-orange-600',
  summaryCard: 'border-blue-200 bg-blue-50',
  summaryContent: 'p-4',
  summaryRow: 'flex items-center justify-between gap-3',
  summaryText: 'text-sm leading-5 text-blue-800',
  summaryHint: 'text-xs leading-5 text-blue-600',
} as const
