import { billDetailMobileStyles } from '@/components/business/bill-detail-mobile-styles'
import { contractListMobileStyles } from '@/components/business/contract-list-mobile-styles'
import { contractDetailMobileStyles } from '@/components/business/contract-detail-mobile-styles'

export const renterDetailMobileStyles = {
  pageSection: billDetailMobileStyles.pageSection,
  actionsRow: contractDetailMobileStyles.actionsGrid,
  actionButton: contractDetailMobileStyles.actionButton,
  card: 'rounded-lg border border-gray-100 shadow-sm gap-3 py-3 sm:gap-6 sm:py-6',
  cardHeader: 'gap-1 px-3 pb-0 sm:gap-1.5 sm:px-6',
  cardTitle: 'text-base sm:text-lg',
  cardContent: 'space-y-3 px-3 pt-0 pb-3 sm:space-y-4 sm:px-6 sm:pb-6',
  sectionBlock: 'border-t pt-3 sm:pt-4',
  sectionTitle: 'mb-2.5 text-sm font-medium text-gray-900 sm:mb-3',
  fieldsGrid: 'grid grid-cols-2 gap-x-3 gap-y-2.5 sm:gap-x-4 sm:gap-y-3',
  fieldWide: 'col-span-2',
  fieldBlock: 'grid content-start gap-0.5 sm:gap-1',
  fieldValueSlot: 'flex min-h-5 items-start',
  fieldLabel: 'text-[11px] font-medium leading-4 text-gray-500 sm:text-xs sm:leading-5',
  fieldValue: 'text-sm leading-5 text-gray-900 sm:leading-6',
  fieldValueStrong: 'text-sm font-medium leading-5 text-gray-900 sm:leading-6',
  fieldValueMono:
    'break-all font-mono text-sm font-medium leading-5 text-gray-900 sm:break-normal sm:leading-6',
  noteBlock: 'space-y-1',
  noteText: 'rounded-md bg-gray-50 p-3 text-sm leading-6 whitespace-pre-wrap text-gray-700',
  statusCard: 'space-y-3 rounded-lg border border-gray-100 bg-gray-50 p-3 sm:p-4',
  statusHeader: 'flex items-start gap-3',
  statusMeta: 'min-w-0 flex-1 space-y-1',
  statusTitle: 'text-sm font-medium leading-5 text-gray-900',
  statusDescription: 'text-xs leading-5 text-gray-600 sm:text-sm',
  statusGrid: 'grid grid-cols-1 gap-2.5 sm:grid-cols-2 sm:gap-3',
  statusField: 'grid content-start gap-0.5',
  statusFieldWide: 'sm:col-span-2',
  statusFieldValue: 'text-sm font-medium leading-5 text-gray-900 sm:leading-6',
  historyCard: 'rounded-lg border border-gray-100 shadow-sm gap-3 py-3 sm:gap-6 sm:py-6',
  historyHeader: 'gap-1 px-3 pb-0 sm:gap-1.5 sm:px-6',
  historyTitle: 'text-base sm:text-lg',
  historyDescription: 'text-sm text-gray-500',
  historyContent: 'px-3 pt-0 pb-3 sm:px-6 sm:pb-6',
  historyList: 'space-y-2.5',
  historyItemCard: contractListMobileStyles.card,
  historyItemContent: contractListMobileStyles.cardContent,
  historyItemHeader: contractListMobileStyles.cardHeader,
  historyItemLeading: contractListMobileStyles.cardLeading,
  historyItemTitle: contractListMobileStyles.cardTitle,
  historyItemMeta: contractListMobileStyles.cardMeta,
  historyItemBadge: contractListMobileStyles.cardBadge,
  historyItemDetails: contractListMobileStyles.detailStack,
  historyItemRow: contractListMobileStyles.detailRow,
  historyItemPairRow: contractListMobileStyles.detailPairRow,
  historyItemLabel: contractListMobileStyles.detailLabel,
  historyItemValue: contractListMobileStyles.detailValue,
  historyItemSecondaryValue: contractListMobileStyles.detailPairValue,
  historyItemFooter: contractListMobileStyles.footer,
  historyItemFooterRow: contractListMobileStyles.footerRow,
  historyItemFooterText: contractListMobileStyles.footerMetaText,
  historyItemFooterSubtle: contractListMobileStyles.footerMetaSubtle,
  historyActionButton: 'h-8 px-3 text-sm text-gray-600 hover:text-gray-800',
  emptyState: 'py-8 text-center text-gray-500',
} as const
