import { billDetailMobileStyles } from '@/components/business/bill-detail-mobile-styles'
import { contractDetailMobileStyles } from '@/components/business/contract-detail-mobile-styles'
import { contractListMobileStyles } from '@/components/business/contract-list-mobile-styles'

export const roomDetailMobileStyles = {
  pageSection: billDetailMobileStyles.pageSection,
  actionsRow: contractDetailMobileStyles.actionsGrid,
  actionButton: contractDetailMobileStyles.actionButton,
  card: billDetailMobileStyles.card,
  cardHeader: billDetailMobileStyles.cardHeader,
  cardHeaderRow: billDetailMobileStyles.cardHeaderRow,
  cardTitle: billDetailMobileStyles.cardTitle,
  cardContent: billDetailMobileStyles.cardContent,
  fieldsGrid: billDetailMobileStyles.fieldsGrid,
  fieldBlock: 'grid content-start gap-0.5 sm:gap-1',
  fieldWide: billDetailMobileStyles.fieldWide,
  fieldLabel: 'text-[11px] font-medium leading-4 text-gray-500 sm:text-xs sm:leading-5',
  fieldValue: 'text-sm leading-5 text-gray-900 sm:leading-6',
  fieldValueStrong: 'text-sm font-medium leading-5 text-gray-900 sm:leading-6',
  fieldValueLarge: 'text-base font-semibold leading-5 text-gray-900 sm:text-lg sm:leading-6',
  sectionBlock: 'border-t pt-3 sm:pt-4',
  sectionTitle: 'mb-2.5 text-sm font-medium text-gray-900 sm:mb-3',
  emptyState: 'py-8 text-center text-gray-500',
  emptyTitle: 'text-base font-medium text-gray-900',
  emptyText: 'mt-1 text-sm text-gray-500',
  currentStatusRow: 'flex items-start gap-2.5',
  currentStatusMeta: 'min-w-0 flex-1 space-y-0.5',
  currentStatusTitle: 'text-sm font-medium leading-5 text-gray-900',
  currentStatusText: 'text-sm leading-5 text-gray-500',
  statusOptionsGrid: 'grid grid-cols-2 gap-2 md:grid-cols-4 sm:gap-2.5',
  statusOptionButton:
    'flex h-auto min-h-[72px] flex-col items-start gap-1.5 rounded-lg px-3 py-2.5 text-left whitespace-normal',
  statusOptionText: 'text-xs font-medium leading-4',
  explanationList: 'space-y-1.5 text-sm leading-5 text-gray-600',
  hintText: 'text-sm leading-5 text-gray-500',
  meterSection: 'space-y-2.5 sm:space-y-4',
  meterHeaderRow: 'flex items-start justify-between gap-2.5',
  meterHeadingGroup: 'space-y-0.5',
  meterTitle: 'text-base font-semibold leading-5 text-gray-900 sm:text-lg',
  meterDescription: 'text-sm leading-5 text-gray-500',
  meterAddButton: 'h-9 gap-1.5 px-3 text-sm',
  meterStatsGrid: 'grid grid-cols-2 gap-2.5 md:grid-cols-4 md:gap-4',
  meterStatsCard: contractListMobileStyles.statsCard,
  meterStatsCardContent: contractListMobileStyles.statsContent,
  meterStatsInner: contractListMobileStyles.statsInner,
  meterStatsLabel: contractListMobileStyles.statsLabel,
  meterStatsValue: contractListMobileStyles.statsValue,
  meterNoticeBox: 'rounded-lg border border-amber-200 bg-amber-50 p-2.5 sm:p-3',
  meterNoticeTitle: 'text-sm font-medium leading-5 text-amber-900',
  meterNoticeText: 'mt-1 text-sm leading-5 text-amber-900/90 sm:leading-6',
  meterGrid: 'grid grid-cols-1 gap-2.5 md:grid-cols-2 xl:grid-cols-3 xl:gap-4',
  meterCard: contractListMobileStyles.card,
  meterCardHeader: 'px-3 pb-0 pt-3 sm:px-4 sm:pt-4',
  meterCardHeaderRow: 'flex items-start justify-between gap-2',
  meterCardTitleRow: 'flex min-w-0 items-center gap-2',
  meterCardName: contractListMobileStyles.cardTitle,
  meterCardMeta: contractListMobileStyles.cardMeta,
  meterStatePill: 'ml-2 rounded-full px-2 py-0.5 text-[11px] font-medium',
  meterCardContent: 'space-y-2.5 px-3 pb-3 pt-0 sm:px-4 sm:pb-4',
  meterInfoStack: 'space-y-1.5',
  meterMetaRow: 'flex items-center gap-1.5 text-[11px] leading-4 text-gray-500',
  meterInfoRow: 'flex items-center justify-between gap-3',
  meterInfoLabel: 'text-[11px] leading-4 text-gray-500',
  meterInfoValue: 'text-sm font-medium leading-5 text-gray-900',
  meterRemark: 'rounded-md bg-gray-50 p-2.5 text-sm leading-5 text-gray-600',
  meterActions: 'flex items-center gap-1.5 border-t border-gray-100 pt-2',
  meterActionButton: 'h-8 px-2.5 text-sm text-gray-600 hover:text-gray-800',
  meterActionDanger: 'text-orange-600 hover:bg-orange-50 hover:text-orange-700',
  meterEmptyState:
    'rounded-lg border border-dashed border-gray-200 bg-gray-50 py-10 text-center',
  meterEmptyIconBox:
    'mx-auto mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-gray-100',
} as const
