import { contractListMobileStyles } from '@/components/business/contract-list-mobile-styles'

export const roomListMobileStyles = {
  ...contractListMobileStyles,
  filterCard: 'rounded-lg border border-gray-100 bg-white p-3 shadow-sm sm:p-4',
  filterPanel: 'space-y-3 sm:space-y-4',
  filterSubsection: 'space-y-2',
  floorSection: 'space-y-2.5 sm:space-y-3',
  floorHeader: 'flex items-start justify-between gap-3',
  floorHeadingGroup: 'flex min-w-0 items-center gap-2.5',
  floorTitle: 'text-sm font-semibold leading-5 text-gray-900 sm:text-base',
  floorMeta: 'text-[11px] leading-4 text-gray-500 sm:text-xs',
  floorStats: 'flex flex-wrap items-center justify-end gap-x-2 gap-y-1 text-[11px] leading-4 sm:text-xs',
  grid: 'grid grid-cols-2 gap-2.5 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8',
  gridCardMinHeight: 'min-h-[84px] sm:min-h-[92px]',
  card: contractListMobileStyles.card,
  cardContent: 'p-2.5',
  cardHeader: 'mb-1 flex items-start justify-between gap-2',
  cardTitle: contractListMobileStyles.cardTitle,
  cardMeta: 'truncate text-[11px] leading-4 text-gray-500',
  cardBadge: 'ml-2 shrink-0 px-2 py-0.5 text-[11px]',
  cardRent: 'text-sm font-medium leading-5 text-gray-900',
  cardHint: 'text-xs font-medium leading-4',
  cardFooter: 'mt-1.5 border-t border-gray-100 pt-1.5',
  cardFooterRow: 'flex items-center justify-between gap-2.5',
  cardFooterText: 'truncate text-[11px] leading-4 text-gray-600',
  cardFooterMeta: 'shrink-0 text-[11px] leading-4 text-gray-500',
  statsSummary: 'text-sm leading-5 text-gray-600',
} as const
